apiVersion: skaffold/v1beta15
kind: Config
build: 
  artifacts:
    - image: aircat-srv-go
#      context: src/aircat-srv
      context: bin
  tagPolicy:
    sha256: {}
deploy:
  kubectl:
    manifests:
    - kubernetes-manifests/**
profiles:
- name: cloudbuild
  build:
    googleCloudBuild: {}

